version: '3.7'

services:
  api:
    build: .
    command: 'npm run start'
    volumes:
      - '.:/app'
    ports:
      - '3000:3000'
    depends_on:
      - mongo   
    links:
      - mongo  
    restart: on-failure
    
  
  mongo:
    image: mongo
    volumes:
      - 'mongo-volume:/data/db'


volumes:
  mongo-volume: